#!/usr/bin/env bash

PROJ_DIR=$HOME/Project
TOOLCHAIN=$PROJ_DIR/tools
GCC=$TOOLCHAIN/aarch64--musl--bleeding-edge-2018.11-1
CLANG=$TOOLCHAIN/snapdragon-llvm-8.0.6-linux64/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64
GCC32=$TOOLCHAIN/gcc-arm-none-eabi-9-2019-q4-major
PATH=$CLANG/bin:$GCC/bin:$GCC32/bin:$HOME/bin:$PATH 
LD_LIBRARY_PATH=$CLANG/lib:$CLANG/lib64:$LD_LIBRARY_PATH
COMPILER=aarch64-buildroot-linux-musl-
COMPILER32=arm-none-eabi-
MODEL=$(basename ~+)
BOOT=$PWD/out/arch/arm64/boot
IMAGE=$BOOT/Image.gz-dtb
DTOUT=$BOOT/dts/
DUMP=$PWD/zip_files
SOURCE=$PWD/source
TOOLS=$TOOLCHAIN/compile-tools
DTBTOOL=dtbTool
PAGESIZE=4096
ANDROID=ten

# tput color output
RF=$(tput setaf 1)
GF=$(tput setaf 2)
GB=$(tput setab 2)
BB=$(tput bold)
NC=$(tput sgr 0)

export KBUILD_OUTPUT=$PWD/out
export ARCH=arm64
export SUBARCH=arm64

